table '_Currency Prompt'
	lineageTag: 74dfacc9-3c4b-47a3-9462-c73f77cd97dc

	/// if(HASONEVALUE('_Currency Prompt'[Currency]),VALUES('_Currency Prompt'[Currency]),"Local")
	measure CurrencyPrompt =
			
			IF (
			    HASONEVALUE ( '_Currency Prompt'[Currency] ),
			    VALUES ( '_Currency Prompt'[Currency] ),
			    "Local"
			)
		lineageTag: 58beccb3-c34c-4b7c-9a0a-7367f9d93caf

	column Currency
		dataType: string
		lineageTag: 7d6f40dc-e0ab-42d8-b35d-97e51d9057de
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	partition '_Currency Prompt-a1fcc823-a0dc-4bcb-9ebf-88408f2958b4' = m
		mode: import
		source =
				let
				    Source = Sql.Database(#"P_ServerName", #"P_DatabaseName"),
				    DWH_V_CurrencyPrompt = Source{[Schema="DWH",Item="V_CurrencyPrompt"]}[Data]
				in
				    DWH_V_CurrencyPrompt

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

