table F_Service_Accuracy
	lineageTag: 05391cea-12ca-45e9-af2f-5bf3acfb5cd1

	measure 'New Measure in Dataset' = ```
			[Service Accuracy] 
			```
		lineageTag: 8e2d1a84-376a-4ed0-849a-4677b0dcba60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KEY_Site
		dataType: string
		lineageTag: 241d1daa-c911-4b65-b4bf-5a43dbbcb086
		summarizeBy: none
		sourceColumn: KEY_Site

		annotation SummarizationSetBy = Automatic

	column KEY_Asset
		dataType: string
		lineageTag: aece3836-76aa-4325-83c5-b9e1b4a9cd7e
		summarizeBy: none
		sourceColumn: KEY_Asset

		annotation SummarizationSetBy = Automatic

	column KEY_WorkOrder
		dataType: string
		lineageTag: c470fb9e-a6a3-4405-84af-5574a3a26f13
		summarizeBy: none
		sourceColumn: KEY_WorkOrder

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: 3ecc50cb-a99b-4ece-a4b0-69d0c84fe98c
		summarizeBy: none
		sourceColumn: Year Month

		annotation SummarizationSetBy = Automatic

	column 'Completed Date'
		dataType: dateTime
		formatString: dd-mmm-yyyy
		lineageTag: 7d099cba-770f-4275-a471-b7cafadef1e8
		summarizeBy: none
		sourceColumn: Completed Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'Set Name'
		dataType: string
		lineageTag: f844a581-8fad-4cd4-ba64-692fe8d7a92e
		summarizeBy: none
		sourceColumn: Set Name

		annotation SummarizationSetBy = Automatic

	column 'Total Hours'
		dataType: double
		lineageTag: 98dee854-dd73-4841-ad2e-e79fd51d20af
		summarizeBy: sum
		sourceColumn: Total Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Meter Reading'
		dataType: double
		formatString: 0
		lineageTag: 1048986c-1dc6-4180-a563-a5eefd9b1c04
		summarizeBy: sum
		sourceColumn: Meter Reading

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Meter Based Flag'
		dataType: double
		formatString: 0
		lineageTag: c8999a40-ec58-4d11-8879-4efba668f6b3
		summarizeBy: sum
		sourceColumn: Meter Based Flag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Meter Compliant Flag'
		dataType: double
		formatString: 0
		lineageTag: 2257532c-56ad-47ab-b4ea-99a3648ec2d5
		summarizeBy: sum
		sourceColumn: Meter Compliant Flag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Meter Non Compliant Flag'
		dataType: double
		formatString: 0
		lineageTag: 9d3c9197-5bc5-4437-9258-704bdfc8d014
		summarizeBy: sum
		sourceColumn: Meter Non Compliant Flag

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Avg Meter Differnce'
		dataType: double
		formatString: 0.00
		lineageTag: ddc49e81-44b3-4dd2-8f0a-47fb37d0a749
		summarizeBy: sum
		sourceColumn: Avg Meter Differnce

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column 'Date Based Flag'
		dataType: double
		formatString: 0
		lineageTag: ce9cef22-617f-4930-a08f-7f77728e15ed
		summarizeBy: sum
		sourceColumn: Date Based Flag

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Date Compliant Flag'
		dataType: double
		formatString: 0
		lineageTag: e29909cc-b2e7-4b56-87f1-00077acbe34d
		summarizeBy: sum
		sourceColumn: Date Compliant Flag

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Date Non Compliant Flag'
		dataType: double
		formatString: 0
		lineageTag: 8667efb3-61d4-4916-9b60-f2e38b5a04f9
		summarizeBy: sum
		sourceColumn: Date Non Compliant Flag

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Avg Date Differnce'
		dataType: double
		formatString: 0.00
		lineageTag: 83375b0f-08c4-4fcd-ac2c-75ec0483b52a
		summarizeBy: sum
		sourceColumn: Avg Date Differnce

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column PM_Type
		dataType: string
		lineageTag: 184da9f1-a7a5-474c-a23f-d6951ad9b499
		summarizeBy: none
		sourceColumn: PM_Type

		annotation SummarizationSetBy = Automatic

	column Month_Num_Key = F_Service_Accuracy[Year Month] & "01"
		lineageTag: 37fa0890-524e-4278-bc6b-4ea6c6bcfd7c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Compliant_Flag
		dataType: double
		formatString: 0
		lineageTag: 5ec7abc5-f962-4975-9fbc-e1dce636d45c
		summarizeBy: sum
		sourceColumn: Compliant_Flag

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Non_Compliant_Flag
		dataType: double
		formatString: 0
		lineageTag: 4b11ec6b-86f6-40d2-aa1b-e2c7ee2fbb74
		summarizeBy: sum
		sourceColumn: Non_Compliant_Flag

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Compliant Flag' = if(F_Service_Accuracy[Compliant_Flag] = 1,"Y","N")
		lineageTag: 89c58f98-a8b2-4d43-95dc-e50af3707584
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date_Compliant_Flag = if(F_Service_Accuracy[Date Compliant Flag] = 1,"Y","N")
		lineageTag: 42f2adfc-037d-4318-8c1f-a2d55671d584
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Meter_Compliant_Flag = if(F_Service_Accuracy[Meter Compliant Flag] = 1,"Y","N")
		lineageTag: c10e8fd6-5613-4d35-9e48-ccb80a66acd0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SourceSystemID
		dataType: string
		lineageTag: 135e8916-d8f0-4ca5-bd20-4c1f845d3687
		summarizeBy: none
		sourceColumn: SourceSystemID

		annotation SummarizationSetBy = Automatic

	column 'New Column in dataset' = YEAR(F_Service_Accuracy[Completed Date])
		formatString: 0
		lineageTag: 6c365eb9-ca3a-4947-ab19-44786cb45374
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition F_Service_Accuracy-7b36b244-05c4-4821-aeb7-17195e13b4af = m
		mode: import
		queryGroup: 'DWH Facts'
		source = ```
				let
				    Source = Sql.Database(P_ServerName, P_DatabaseName),
				    DWH_F_Service_Accuracy = Source{[Schema="DWH",Item="F_Service_Accuracy"]}[Data],
				    // parameter values
				    // 
				    #"Filtered Rows" = Table.SelectRows(DWH_F_Service_Accuracy, each [Completed_Date] >= P_Date_From),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"Asset_Number", "Asset Number"}, {"Avg_Meter_Differnce", "Avg Meter Differnce"}, {"Completed_Date", "Completed Date"}, {"Country_Code", "Country Code"}, {"Meter_Based_Flag", "Meter Based Flag"}, {"Meter_Reading", "Meter Reading"}, {"Meter_Non_Compliant_Flag", "Meter Non Compliant Flag"}, {"Set_Name", "Set Name"}, {"Total_Hours", "Total Hours"}, {"WorkOrder_Number", "WorkOrder Number"}, {"Year_Month", "Year Month"}, {"Meter_Compliant_Flag", "Meter Compliant Flag"}, {"Date_Based_Flag", "Date Based Flag"}, {"Date_Compliant_Flag", "Date Compliant Flag"}, {"Date_Non_Compliant_Flag", "Date Non Compliant Flag"}, {"Avg_Date_Differnce", "Avg Date Differnce"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"KEY_Site", "KEY_Asset", "KEY_WorkOrder", "Year Month", "Completed Date", "Set Name", "Total Hours", "Meter Reading", "Compliant_Flag", "Non_Compliant_Flag", "Meter Based Flag", "Meter Compliant Flag", "Meter Non Compliant Flag", "Avg Meter Differnce", "Date Based Flag", "Date Compliant Flag", "Date Non Compliant Flag", "Avg Date Differnce", "PM_Type", "SourceSystemID"})
				in
				    #"Removed Other Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

