table LKP_WO_Status
	lineageTag: 0821c2ab-8411-445b-a3fd-a1f3b0ce7979

	column 'Work Order Status Description'
		dataType: string
		lineageTag: 891e1da7-8ac5-4f1e-9c17-32226141bf9b
		summarizeBy: none
		sourceColumn: Work Order Status Description

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 25ba4c7f-0516-4a1f-a0f8-f757623a29d5
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition LKP_WO_Status-6ba89240-5e00-4bd5-b77d-e5322e058ac1 = m
		mode: import
		queryGroup: 'Lookup Files'
		source =
				let
				    Source = SharePoint.Tables("https://hsconline.sharepoint.com/sites/mmbiteam", [Implementation="2.0", ViewMode="Default"]),
				    #"fb6811c5-b7a9-483d-a9bc-081d2ab85a07" = Source{[Id="fb6811c5-b7a9-483d-a9bc-081d2ab85a07"]}[Items],
				    #"Removed Other Columns" = Table.SelectColumns(#"fb6811c5-b7a9-483d-a9bc-081d2ab85a07",{"Work Order Status Description", "Status"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

