table 'Maintenance Types'
	lineageTag: 7eec0036-8ac1-4a69-9ece-e6cf98494901

	column 'WO Type'
		dataType: string
		lineageTag: f04e5d5c-b5de-4629-b284-51d46011ed90
		summarizeBy: none
		sourceColumn: WO Type

		annotation SummarizationSetBy = Automatic

	column 'Maintenance Type'
		dataType: string
		lineageTag: 72206d84-19a4-4bb3-96a7-56f545b1bfe3
		summarizeBy: none
		sourceColumn: Maintenance Type

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: 4dae727c-2e42-412e-8c05-e0fb04d04079
		summarizeBy: sum
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	partition 'Maintenance Types-3237e2ff-46a4-4965-9b48-f93974d2c4a9' = m
		mode: import
		queryGroup: 'Scheduled Compliance'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZDLisMwDEV/xWRdNMzjBxRbSd06tvGjpYQuOq1hCsMUQsj3jxOyCWlXFjrHF0ltWyCUjnAvzFEXmwKHx/12+f5Nuf4szpu2KME6IyIP0mjGMXoSbwIbrOmpzsEq1JoE48Y5yt8Oo8gfXZeu/X0YzY/JFDmYDqRnw3ZpSH/9ZXbeJ4fAY0XhlBum/0ldfr8mUAE3jVUSNacVrMERE2bV346r7PJMKyLBb2OYb7BEO0DRSC19cDiPuhT2UEVSTHof11ABRysDqteE4RFlkLpmWMmV1oCKJfkX8SZvqp+lW/DR5vuQX6LzPw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"WO Type" = _t, #"Maintenance Type" = _t, #"Sort Order" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"WO Type", type text}, {"Maintenance Type", type text}, {"Sort Order", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

